[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://sistema-pedidos-restaurante.onrender.com"
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
